# Generated by Django 4.1.2 on 2022-11-03 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100, verbose_name='возраст')),
                ('height', models.CharField(blank=True, max_length=10, verbose_name='выстота')),
                ('weight', models.CharField(blank=True, max_length=100, verbose_name='вес')),
                ('blood_type', models.CharField(blank=True, max_length=10, verbose_name='группа крови')),
                ('allergy', models.CharField(blank=True, max_length=100, verbose_name='аллергия на что либо')),
                ('symptoms', models.CharField(blank=True, max_length=500, verbose_name='симптомы')),
                ('disability', models.CharField(blank=True, max_length=100, verbose_name='инвалидность')),
                ('injury', models.CharField(blank=True, max_length=100, verbose_name='травма')),
                ('illness', models.CharField(max_length=100, verbose_name='болезнь')),
                ('person_images', models.ImageField(blank=True, upload_to='person_image/', verbose_name='фотография')),
                ('name', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
